name: NOT_LSTM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py310h458dff3_0
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.19=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - et_xmlfile=2.0.0=py310haa95532_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2025.3.0=h57928b3_641
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang13=21.1.7=default_ha2db4b5_3
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.86.2=hd9c3897_0
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=13_h018ca30_netlib
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.53=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.1=hf5d6505_1
  - libtiff=4.7.1=h8f73337_1
  - libuv=1.51.0=hfd05255_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxgboost=3.1.2=h585ebfc_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzlib=1.3.1=h2466b09_2
  - lxml=5.3.0=py310h985e36a_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2023.1.0=h6a75c08_48682
  - mkl-service=2.4.0=py310h827c3e9_2
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310h4987827_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py310h827c3e9_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py310h3e38d90_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py310h1637853_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=py310haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.9.2=py310h2d19612_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-docx=1.2.0=pyhff2d567_0
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py310h282bd7d_1
  - pyyaml=6.0.3=py310hdb0e946_0
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.2=ha0de62e_3
  - requests=2.32.5=pyhcf101f3_1
  - scipy=1.15.3=py310h180bac5_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h62715c5_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py310h29418f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xgboost=3.1.2=py310haa95532_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h534d264_6
  - pip:
      - joblib==1.5.3
      - panda==0.3.1
      - pandas==2.3.3
      - pandas-stubs==2.3.3.251219
      - pytz==2025.2
      - scikit-learn==1.7.2
      - threadpoolctl==3.6.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tzdata==2025.3
prefix: D:\Github\anaconda3\envs\NOT_LSTM
